python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py

python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py

python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
python3 test/rgb.py
python3 test/rgbi.py
