python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py

python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py

python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py

python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
python3 test/cg_rgb.py
python3 test/cg_rgbi.py
