python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
python3 test/cg_rgbd.py
